Repository geoschem/HEMCO, pull requests merged in 2023-07, with the labels that each got.

#215 Update Hg0 Emission Factors in hcox_gfed_include_gfed4.H
  src/Extensions/hcox_gfed_include_gfed4.H
Labels: bug, extensions

#218 Remove redundant code in hco_extlist_mod.F90
  CHANGELOG.md
  src/Core/hco_extlist_mod.F90
Labels: feature, structural, zero-diff update

#223 Change GEOS-IT meteorology constants year from 2011 to 2018
  src/Core/hco_extlist_mod.F90
Labels: data sources / I-O

#221 Print HEMCO verbose status and volcano extension on root thread only
  src/Core/hco_config_mod.F90
  src/Extensions/hcox_volcano_mod.F90
Labels: bug

#226 Update netCDF code (in src/Shared/NcdfUtil) to use the netCDF-F90 interface
  CHANGELOG.md
  src/Core/hcoio_write_std_mod.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_checks.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_close.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_create.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_define.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_get_dimlen.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_handle_err.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_open.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_read.F90
  src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90
  src/Shared/NcdfUtil/hco_ncdf_mod.F90
  src/Shared/NcdfUtil/m_do_err_out.F90
Labels: feature, interface to external model, structural, zero-diff update

#229 Fix incorrect longitude definition in HEMCO_sa_Grid.025x0625.rc and HEMCO_sa_Grid.05x0625.rc
  CHANGELOG.md
  run/HEMCO_sa_Grid.025x03125.rc
  run/HEMCO_sa_Grid.05x0625.rc
  run/HEMCO_sa_Grid.2x25.rc
  run/HEMCO_sa_Grid.4x5.rc
Labels: bug, standalone

#230 Fix bug in volcano extension causing crash when volcano turned off
  src/Extensions/hcox_volcano_mod.F90
Labels: bug
