Repository geoschem/HEMCO, pull requests merged in 2023-02, with the labels that each got.

#182 Reduce logfile output in HEMCO, and combine Verbose and Warnings into a single switch
  CHANGELOG.md
  run/HEMCO_Config.rc.sample
  run/HEMCO_sa_Config.template
  src/Core/hco_calc_mod.F90
  src/Core/hco_clock_mod.F90
  src/Core/hco_config_mod.F90
  src/Core/hco_datacont_mod.F90
  src/Core/hco_diagn_mod.F90
  src/Core/hco_emislist_mod.F90
  src/Core/hco_error_mod.F90
  src/Core/hco_extlist_mod.F90
  src/Core/hco_geotools_mod.F90
  src/Core/hco_interp_mod.F90
  src/Core/hco_logfile_mod.F90
  src/Core/hco_readlist_mod.F90
  src/Core/hco_restart_mod.F90
  src/Core/hco_scale_mod.F90
  src/Core/hco_state_mod.F90
  src/Core/hco_timeshift_mod.F90
  src/Core/hco_vertgrid_mod.F90
  src/Core/hcoio_messy_mod.F90
  src/Core/hcoio_read_mapl_mod.F90
  src/Core/hcoio_read_std_mod.F90
  src/Core/hcoio_util_mod.F90
  src/Core/hcoio_write_std_mod.F90
  src/Extensions/hcox_custom_mod.F90
  src/Extensions/hcox_dustdead_mod.F
  src/Extensions/hcox_dustginoux_mod.F90
  src/Extensions/hcox_finn_mod.F90
  src/Extensions/hcox_gc_POPs_mod.F90
  src/Extensions/hcox_gc_RnPbBe_mod.F90
  src/Extensions/hcox_gfed_mod.F90
  src/Extensions/hcox_iodine_mod.F90
  src/Extensions/hcox_lightnox_mod.F90
  src/Extensions/hcox_megan_mod.F90
  src/Extensions/hcox_paranox_mod.F90
  src/Extensions/hcox_seaflux_mod.F90
  src/Extensions/hcox_seasalt_mod.F90
  src/Extensions/hcox_soilnox_mod.F90
  src/Extensions/hcox_state_mod.F90
  src/Extensions/hcox_template_mod.F90x
  src/Extensions/hcox_tomas_dustdead_mod.F
  src/Extensions/hcox_tomas_jeagle_mod.F90
  src/Extensions/hcox_volcano_mod.F90
  src/Interfaces/MAPL_ESMF/hcoi_esmf_mod.F90
Labels: feature, config-files / rundir, structural, zero-diff update

#191 GEOS-only updates by Christoph Keller
  CHANGELOG.md
  src/Core/hco_restart_mod.F90
  src/Extensions/hcox_dustdead_mod.F
Labels: interface to external model

#194 Remove memory leaks in HEMCO core and standalone routines (closes #190)
  CHANGELOG.md
  src/Core/hco_arr_mod.F90
  src/Core/hco_config_mod.F90
  src/Core/hco_datacont_mod.F90
  src/Core/hco_filedata_mod.F90
  src/Core/hco_geotools_mod.F90
  src/Core/hco_readlist_mod.F90
  src/Extensions/hcox_dustdead_mod.F
  src/Extensions/hcox_tomas_dustdead_mod.F
  src/Interfaces/Standalone/hcoi_standalone_mod.F90
Labels: feature, performance / parallelization

#195 Simplify Github issue and pull request templates
  .github/ISSUE_TEMPLATE/ask-a-question-about-hemco.md
  .github/ISSUE_TEMPLATE/new-feature-or-discussion.md
  .github/ISSUE_TEMPLATE/question-issue.md
  .github/ISSUE_TEMPLATE/report-a-bug-or-technical-issue.md
  .github/ISSUE_TEMPLATE/request-a-new-feature.md
  .github/ISSUE_TEMPLATE/start-a-hemco-discussion.md
  .github/ISSUE_TEMPLATE/version-release-checklist.md
  .github/PULL_REQUEST_TEMPLATE/create_a_hemco_pull_request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request.md
  CHANGELOG.md
  CONTRIBUTING.md
  SUPPORT.md
Labels: documentation, zero-diff update

#193 Throw an error if HEMCO reads netCDF data on 360_day, 365_day, or noleap calendars
  CHANGELOG.md
  src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90
  src/Shared/NcdfUtil/hco_ncdf_mod.F90
Labels: bug, data sources / I-O
