Repository geoschem/HEMCO, pull requests merged in 2025-03, with the labels that each got.

#306 Turn off map_a2a pole-averaging when using CESM
  CHANGELOG.md
  src/Core/hco_config_mod.F90
  src/Core/hco_readlist_mod.F90
  src/Shared/GeosUtil/hco_regrid_a2a_mod.F90
Labels: topic: ESMF or MPI, category: Interface to External Model

#311 Fix improper handling of date timestamps and lat/lon bounds for mask files
  CHANGELOG.md
  src/Core/hco_config_mod.F90
  src/Core/hco_logfile_mod.F90
  src/Core/hco_types_mod.F90
Labels: category: Bug Fix

#317 Add commented out debug code useful for MPI debugging
  CHANGELOG.md
  src/Core/hco_calc_mod.F90
  src/Core/hco_geotools_mod.F90
  src/Core/hcoio_messy_mod.F90
  src/Core/hcoio_read_std_mod.F90
Labels: category: Feature Request, topic: Benchmarking and Testing

#290 Add capability to run HEMCO at 0.125x0.15625 resolution
  CHANGELOG.md
  run/HEMCO_sa_Grid.0125x015625.rc
  run/createRunDir.sh
  src/Core/hco_config_mod.F90
  src/Core/hco_extlist_mod.F90
Labels: topic: Structural Modifications
